=== Nadamellithy/XML/familydtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ENTER_NAME_OF_ROOT_ELEMENT_HERE EMPTY>
<!ELEMENT Family (grandFather) >
<!ELEMENT grandFather (Father , (uncle)+, Aunt)>
<!ELEMENT Father (Mother , Daughter , Son) >
<!ELEMENT Mother (#PCDATA) >
<!ELEMENT Daughter (#PCDATA)>
<!ELEMENT Son (#PCDATA) >
<!ELEMENT uncle (#PCDATA)>
<!ELEMENT Aunt (#PCDATA)>

<!ATTLIST Father job  (Engineer | Accountant | Doctor) 'Engineer'>
<!ATTLIST Daughter job  (Engineer | Accountant | Doctor) "Engineer">

<!ATTLIST Son age NMTOKEN  #REQUIRED>
<!ATTLIST Daughter age NMTOKEN  #REQUIRED>

<!ATTLIST Son sport ( tennis | football ) "football" >
<!ATTLIST Aunt sons CDATA  #IMPLIED>

=== Nadamellithy/XML/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by www.serials.ws (www.serials.ws) -->
<!DOCTYPE Family SYSTEM "C:\Users\Microsoft\Documents\Altova Projects\familydtd.dtd">
<Family>
	<grandFather>
		<Father job="Doctor">
			<Mother/>
			<Daughter age="12" job="Doctor"/>
			<Son age="4" sport="tennis"/>
		</Father>
		<uncle/>
		<uncle/>
		<Aunt sons="4"/>
	</grandFather>
</Family>
